### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by lgmautner** [red56/django-immutablemodel#7]
https://github.com/blog/1530-choosing-an-open-source-license

**Comment by timdiggins** [comment]
hey @lgmautner, thanks  I'm not doing too much on this project, but I'd go for an MIT licences on new opensource projects. If you add an MIT license as a PR, I'll merge it!

**Comment by lgmautner** [comment]
Sure thing! https://github.com/red56/django-immutablemodel/pull/8
